map $request_method $books_upstream {
    default command_service;
    GET     query_service;
}

upstream command_service {
    server command-service:8000;
}

upstream query_service {
    server query-service:8000;
}

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/books {
        proxy_pass http://$books_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
